### ISSUE TITLE
Warning: literal string will be frozen in the future

### ISSUE THREAD

**Issue by fcwheat** [launchdarkly/ruby-eventsource#56]
We are on Ruby version `3.4.4` and `ld-eventsource` version `2.2.3` and we recently enabled deprecation warnings within our development environment via: `Warning[:deprecated] = true`.

In doing this we are seeing a repeated warning coming from `ld-eventsource`. The warning is:

```bash
/usr/local/bundle/gems/ld-eventsource-2.2.3/lib/ld-eventsource/impl/buffered_line_reader.rb:27: warning: literal string will be frozen in the future (run with --debug-frozen-string-literal for more information)
```

Here is a [link](https://github.com/launchdarkly/ruby-eventsource/blob/2.2.3/lib/ld-eventsource/impl/buffered_line_reader.rb#L27) to that line. Would the LD team be able to review this and consider fixing for a future release?

**Comment by keelerm84** [comment]
Thank you for bringing this to our attention. Yes, we can definitely take a look at this. I will update you here once I've had time to work on it.

**Comment by keelerm84** [comment]
@fcwheat this has been fixed and released in v2.2.5! Thank you again for bringing it to our attention.

**Comment by keelerm84** [comment]
@fcwheat I have released 8.10.2 which includes this fix.

**Comment by fcwheat** [comment]
@keelerm84 just a heads up we are still seeing this with the latest version:

<img width="1502" height="49" alt="Image" src="https://github.com/user-attachments/assets/be89dbbc-22e4-45a7-9cdd-1aac5f3c2a7b" />

**Comment by keelerm84** [comment]
@fcwheat we have released 8.11.0 which addresses some more of these warnings. Please let me know if you experience any further issues. And thank you for your patience.

**Comment by fcwheat** [comment]
@keelerm84 we haven't seen any further issues since the update - thanks!

**Comment by keelerm84** [comment]
> @keelerm84 we haven't seen any further issues since the update - thanks!

Appreciate you following up with me. Have a great rest of your week!
